before:
  hooks:
    - go mod download
    # - go generate ./...
builds:
- env:
    - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows
  ignore:
    - goos: darwin
      goarch: 386
archives:
- name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
